apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mqtt-deployment
spec:
  selector:
    matchLabels:
      app: mqtt
  replicas: 1
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      nodeSelector:
        dedicated: master
      containers:
      - name: mqtt
        image: eclipse-mosquitto 
        ports:
        - containerPort: 1883

