apiVersion: apps/v1 
kind: Deployment
metadata:
  name: process-demo-simulate-deployment
spec:
  selector:
    matchLabels:
      app: process-demo-simulate
  replicas: 1
  template:
    metadata:
      labels:
        app: process-demo-simulate
    spec:
      nodeSelector:
        dedicated: master
      containers:
      - name: process-demo-simulate
        image: tbiernat/process-demo-simulate 
